server:
  port: 18082

spring:
  application:
    name: activemq-consumer
  activemq:
    in-memory: true
    pool:
      enabled: false
    broker-url: failover:(tcp://10.103.106.83:61616,tcp://10.103.106.97:61616,tcp://10.103.106.104:61616)
  jms:
    pub-sub-domain: true
  redis:
    database: 4
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数
        max-idle: 10  # 连接池中的最大空闲连接
        max-wait: 1  # 连接池最大阻塞等待时间
    password: gxatek#redis
    sentinel:
      master: redis_6379
      nodes: 10.103.106.76:16379,10.103.106.90:16379,10.103.106.46:16379
    timeout: 2000
